### ISSUE TITLE
pandeia_data-1.5_wfirst/normalization/alpha_lyr_stis_008.fits file not found error

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#123]
I am getting the following error on a new STIPS installation:

>>> print(observation['filters'], obm.instrument.zeropoint)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ben/src/STScI-STIPS/stips/instruments/instrument.py", line 961, in zeropoint
    sp = syn.SourceSpectrum.from_vega()
  File "/Users/ben/miniconda3/envs/stips/lib/python3.7/site-packages/synphot/spectrum.py", line 1383, in from_vega
    filename, **kwargs)
  File "/Users/ben/miniconda3/envs/stips/lib/python3.7/site-packages/synphot/specio.py", line 52, in read_remote_spec
    show_progress=show_progress) as fd:
  File "/Users/ben/miniconda3/envs/stips/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/ben/miniconda3/envs/stips/lib/python3.7/site-packages/astropy/utils/data.py", line 252, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ben/src/STScI-STIPS/pandeia_data-1.5_wfirst/normalization/alpha_lyr_stis_008.fits'
>>> 

I have older STIPS installations that do not have this error, but that file does not appear in the pandeia data directory in that installation either.  I'm not sure why my new installation looks for this file, but my older one (which has the same version of the software) does not.

**Comment by benw1** [comment]
This issue was fixed with the proper synphot files. The links in readthedocs were out of data. Closing.
