### ISSUE TITLE
Sky level changes with oversampling in Z087 band

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#17]
We are finding that if we run the same parameters for STIPS image creation in the Z087 band, but set the oversampling to 1, we get about a factor of 2 higher background than if we set the oversampling to be >1.  The same is *not* true of the other bands, so it appears there is some problem with inserting background in the z087 band for oversampling of 1.

**Comment by york-stsci** [comment]
I think that I've figured out what's going on, and the fix should be (as with several other fixes), in the square_pixel_fix branch. Please test for this issue there.

**Comment by benw1** [comment]
Using the square_pixel_fix, the Z087 filter oversampling=1 images still have a factor of 2 higher background.

**Comment by york-stsci** [comment]
Please attach (or paste in) logging output from running Z087 at two different oversampling levels, as well as attaching the HISTORY sections of the headers of the resulting FITS files.

**Comment by benw1** [comment]
This latest version also is not properly inserting Sersic profiles.  In previous versions, our input Sersic sources had significant flux levels.  E.g., 
comment: surface brightness 6.917 yielded flux 0.199
Now they mostly yield zero flux:
comment: surface brightness 6.917 yielded flux 0.000

**Comment by york-stsci** [comment]
And you have turned off other noise sources, so it's definitely caused by the background count rate?

**Comment by york-stsci** [comment]
Re. Sersic profiles, please open another issue for this.

**Comment by benw1** [comment]
I did not turn off anything.  Here is the header info for the 10x oversampling for the noise:
HISTORY Adding Poisson Noise with mean 0.00721852714196 and standard deviation 7
HISTORY 7.6421966553                                                            
HISTORY Adding Read noise with mean 0.003098 and standard deviation 11.999038   
HISTORY Adding Flatfield residual with mean 1.009788 and standard deviation 0.00
HISTORY 0677                                                                    
HISTORY Adding Dark residual with mean 6.935139 and standard deviation 36.687622
HISTORY Adding Cosmic Ray residual with mean 8.368157 and standard deviation 15.
HISTORY 858943                                                           

And for the 1x oversampling
HISTORY Adding Poisson Noise with mean 0.00175474863499 and standard deviation 1
HISTORY 00.746574402                                                            
HISTORY Adding Read noise with mean -0.000837 and standard deviation 11.995907  
HISTORY Adding Flatfield residual with mean 1.009788 and standard deviation 0.00
HISTORY 0677                                                                    
HISTORY Adding Dark residual with mean 6.935139 and standard deviation 36.687622
HISTORY Adding Cosmic Ray residual with mean 8.366576 and standard deviation 15.
HISTORY 856685

**Comment by york-stsci** [comment]
Please do another run, this time turning off flatfield, dark, poisson noise, readnoise, and cosmic ray residuals for both, and see if the problem persists. Because it reports the same value being added in both cases, I'm not convinced that the sky level is actually the problem.

**Comment by benw1** [comment]
Indeed it is hard to be sure where the offset is coming from with the current tests.  Please send the syntax for turning all of those other attributes off, and I will run it.

**Comment by york-stsci** [comment]
When creating the observation module, pass it a dictionary with the keyword "residual". The dictionary should contain keys named "flat", "dark", "cosmic", "poisson", and "readnoise", all set to False.

**Comment by york-stsci** [comment]
Again, please provide logging output for this run. Without it, it's very hard for me to figure out what actually happened at every stage of the simulation. In addition, please update to the newest commit on the square_pixel_fix branch and include `snapshots={'all'}` in the input to the `obm.addError()` function (or, in the current version, include `snapshots={'initial', 'background', 'exptime', 'convolve', 'poisson', 'flat', 'dark', 'cr'}` in the current version). This should create images of the partially-complete simulation at the corresponding points, and it would be useful if you can tell me which of those image(s) show the difference with oversampling.

Also, to confirm, this bug *only* applies to the Z087 filter, and *only* oversample=1 is inconsistent with the other oversample levels, correct?

**Comment by benw1** [comment]
Here is the log.  Yes, only the Z087 oversample=1.
[no_noise_z087_os1.log.gz](https://github.com/spacetelescope/STScI-STIPS/files/2531755/no_noise_z087_os1.log.gz)
I will attempt to update and report back.

**Comment by benw1** [comment]
I get an error:
Traceback (most recent call last):
  File "run_stips_86.py", line 1, in <module>
    from stips.observation_module import ObservationModule
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/__init__.py", line 5, in <module>
    automodinit.automodinit(__name__, __file__, globals())
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/site-packages/automodinit-0.16-py2.7.egg/automodinit/automodinit.py", line 48, in automodinit
    module=loader.find_module(fullmodulename2).load_module(fullmodulename2)
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/instruments/__init__.py", line 4, in <module>
    automodinit.automodinit(__name__, __file__, globals())
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/site-packages/automodinit-0.16-py2.7.egg/automodinit/automodinit.py", line 48, in automodinit
    module=loader.find_module(fullmodulename2).load_module(fullmodulename2)
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/instruments/hst_instrument.py", line 5, in <module>
    from .instrument import Instrument
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/instruments/instrument.py", line 24, in <module>
    from CStringIO import StringIO
ImportError: No module named CStringIO

**Comment by york-stsci** [comment]
Okay. I misspelled the module name when it's being run under python 2. Should be fixed.

**Comment by benw1** [comment]
Different error:
Traceback (most recent call last):
  File "run_stips_86.py", line 18, in <module>
    psf_file = obm.addError(snapshots={'all'})
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/observation_module/observation_module.py", line 278, in addError
    self.instrument.addError(poisson=self.poisson, readnoise=self.readnoise, flat=self.flat, dark=self.dark, cosmic=self.cosmic, *args, **kwargs)
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/instruments/instrument.py", line 754, in addError
    detector.toFits(self.imgbase+"_{}_{}_snapshot_background.fits".format(self.obs_count, detector.name))
AttributeError: 'WFI' object has no attribute 'imgbase'

**Comment by york-stsci** [comment]
Oh. I forgot to propagate imgbase through from ObservationModule to Instrument. Most recent version should fix that.

**Comment by benw1** [comment]
Ok.  This ran, and produced snapshots in addition to the final file.  What would you like me to check?

**Comment by benw1** [comment]
background image is mostly pixels with value 0.58
exptime image is mostly 5827.3
convolve is mostly ~9414

**Comment by york-stsci** [comment]
And that's the same regardless of oversample?

**Comment by york-stsci** [comment]
What needs to be checked is pretty much when the oversampled snapshots start being unexpectedly different from the non-oversampled snapshots (the expected difference is that the oversampled snapshots are bigger until after they've been binned, and the per-pixel count rate in areas without sources should be lower by a factor of oversample^2 in the oversampled images, again until binning). Basically I'm trying to figure out when the count rates start being different, which should hopefully tell me what's causing the difference.

**Comment by benw1** [comment]
In 4x4 oversampling case, the background image has pixel values of 0.0364 (~0.58/16)
exptime is mostly 364.2 (5827/16)
convolve is 362... that is 9414/26 instead of 9414/16 so perhaps something is up there?

**Comment by benw1** [comment]
I get an error with the current version:
Traceback (most recent call last):
  File "/gscratch/astro/benw1/data/Wpipelines/testpipe4/data/fake_test/conf_default/run_stips_159.py", line 17, in <module>
    psf_file = obm.addError()
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/observation_module/observation_module.py", line 278, in addError
    self.instrument.addError(poisson=self.poisson, readnoise=self.readnoise, flat=self.flat, dark=self.dark, cosmic=self.cosmic, *args, **kwargs)
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/instruments/instrument.py", line 782, in addError
    detector.introduceReadnoise(rn)
  File "/gscratch/astro/benw1/miniconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/astro_image/astro_image.py", line 952, in introduceReadnoise
    raise e
NameError: global name 'seed' is not defined

**Comment by york-stsci** [comment]
Should be fixed.

**Comment by york-stsci** [comment]
Also, I'm assuming you got the PSF back during your calculation. Does either the oversampled PSF or the non-oversampled PSF for Z087 look odd (or too bright) to you?

**Comment by york-stsci** [comment]
I think this is another issue where getting me as much logging information as possible would be useful, just so that I can see what it's doing here.

**Comment by benw1** [comment]
Here are the logs:
[z087_os4.log.gz](https://github.com/spacetelescope/STScI-STIPS/files/2536702/z087_os4.log.gz)
[z087_os1.log.gz](https://github.com/spacetelescope/STScI-STIPS/files/2536704/z087_os1.log.gz)

**Comment by york-stsci** [comment]
Thank you. I've just pushed a new version that adds the PSF total flux to logging. Could you try this version with oversample=1, 4, [some other value], and potentially with Z087 and something else? Doesn't need to be a big scene (in fact probably better if it isn't in order to generate less logging material), I'm mostly interested in what the reported PSF total flux is.

**Comment by benw1** [comment]
Here are the logs.   1 and 4 are the oversampled and the ones with y in the name are Y106.
[run4y.log](https://github.com/spacetelescope/STScI-STIPS/files/2539255/run4y.log)
[run4.log](https://github.com/spacetelescope/STScI-STIPS/files/2539256/run4.log)
[run1y.log](https://github.com/spacetelescope/STScI-STIPS/files/2539257/run1y.log)
[run1.log](https://github.com/spacetelescope/STScI-STIPS/files/2539258/run1.log)

**Comment by york-stsci** [comment]
Okay, just pushed a new version of the code, which I hope will include a fix for this issue. Essentially I've asked webbpsf to normalize the PSF at the end of the optical system, because ultimately I don't want the PSF convolution to be either adding flux to (or removing flux from) anything.

**Comment by benw1** [comment]
setup.py error:
Extracting stips-1.0.0rc6-py3.6.egg to /gscratch/astro/benw1/miniconda3/lib/python3.6/site-packages
  File "/gscratch/astro/benw1/miniconda3/lib/python3.6/site-packages/stips-1.0.0rc6-py3.6.egg/stips/instruments/nircam.py", line 73
    psf = ins.calcPSF(oversample=self.oversample, fov_pixels=min(max_safe_size, max_ins_size, max_conv_size) normalize='last')
                                                                                                                     ^
SyntaxError: invalid syntax

**Comment by york-stsci** [comment]
Fixed.
