### ISSUE TITLE
Detailed installation documentation required

### ISSUE THREAD

**Issue by rubab1** [spacetelescope/STScI-STIPS#2]
Using the current version with the recommended WebbPSF, PySynohot and Pandeia versions within an AstroConda setup fails to run, as described below. One of the key issues are STIPS scripts searching for PySynphot files that are not part of the current STScI distributions.

Specially, the Documentation needs to describe:
- How to setup STIPS either within an AstroConda or other python setup
- Where the required PySynphot, WebbPSF and Pandeia data can be retrieved from

===

Despite many attempts, the nearby galaxies SIT at UW Seattle has been unable to install/run STIPS locally.  The following are from Meredith Durbin's notes. All runs were with Python2, webbpsf, pysynphot, pandeia-engine-1.0 within an AstroConda setup.

First issue: The code seems to expect files for pysynphot  / CDBS that does not exist.
```
lines 23-25 of wfirst_instrument.py:
        self.REFS = {   'comptable': self.COMPFILES[-2],

                        'graphtable': self.GRAPHFILES[-2],

                        'thermtable': self.THERMFILES[-2],

and lines 37-39 of instrument.py:

        self.COMPFILES =  sorted(glob.glob(os.path.join(os.environ["PYSYN_CDBS"],"mtab","*tmc.fits")))

        self.GRAPHFILES = sorted(glob.glob(os.path.join(os.environ["PYSYN_CDBS"],"mtab","*tmg.fits")))


        self.THERMFILES = sorted(glob.glob(os.path.join(os.environ["PYSYN_CDBS"],"mtab","*tmt.fits")))
```
In the current downloadable set of cdbs tarfiles (ftp://archive.stsci.edu/pub/hst/pysynphot/synphot1.tar.gz specifically) there is only 1 of each of these files. 
temp fix / Hack: downloaded some old versions from ftp://ftp.stsci.edu/cdbs/mtab/OLD_FILES/ to the same directory.

2. Next error: 
``` 
IOError: [Errno 2] No such file or directory: '/Users/luxemburg/grp/hst/cdbs/standards/alpha_lyr_stis_007.fits'
```

temp fix / Hack:  duplicated cdbs 'calspec' directory, which does contain alpha_lyr_stis_007.fits, and renamed to 'standards'. To my knowledge there is no 'standards' directory currently included in the cdbs tarfile release.

**Comment by rubab1** [comment]
Attempting WFI example in README file fails with **KeyError: 'det_type'** 
at obm.nextObservation()
from  pandeia/engine/instrument.py  line 628
( pandeia/engine/instrument.py
pandeia/engine/wfirst.py
pandeia/engine/instrument_factory.py
stips/instruments/instrument.py
stips/observation_module/observation_module.py )

Details follow, from installation to failure.

Installation, including jwst_backgrounds (Note: please add this to README as a requirement)
```
conda create -n forSTIPS python=2.7.12 astropy=1.3.2 numpy=1.12.1 scipy=0.18.1 photutils=0.3.2 pysynphot=0.9.8.5 webbpsf=0.6
source activate forSTIPS
pip install "esutil==0.6.0"
pip install "pandeia.engine==1.1.1"
pip install "montage-wrapper==0.9.9"
pip install "jwst_backgrounds==1.1.1"
```
Paths added to environment
```
export PYSYN_CDBS="/local/tmp/Work/bin/grp/hst/cdbs"
export pandeia_refdata="/local/tmp/Work/bin/pandeia_data-1.1.1"
export stips_data="/local/tmp/Work/STScI-STIPS-UI/sim_input/stips_data"
```
Paths verified
```
$ echo $stips_data
/local/tmp/Work/STScI-STIPS-UI/sim_input/stips_data
$ echo $pandeia_refdata
/local/tmp/Work/bin/pandeia_data-1.1.1
$ echo $PYSYN_CDBS
/local/tmp/Work/bin/grp/hst/cdbs
```
Checked out current STScI-STIPS and STScI-STIPS-UI repo and installed from bugfix branch. Installation completed without any error messages.
```
$ cd /local/tmp/Work/STScI-STIPS
$ git checkout bugfix
$ python setup.py install
```
Following example in README:
```
(forSTIPS) bash-4.2$ python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from stips.observation_module import ObservationModule
>>> obs = {'instrument': 'WFI', 'filters': ['H158'], 'detectors': 1, 'distortion': False, 'oversample': 5, 'pupil_mask': '', 'background': 'avg', 'observations_id': 1, 'exptime': 1000, 'offsets': [{'offset_id': 1, 'offset_centre': False, 'offset_ra': 0.5, 'offset_dec': 0.0, 'offset_pa': 27.0}]}
>>> scene_general = {'ra': 256.274799731, 'dec': 22.6899695529, 'pa': 0.0, 'seed': 1}
>>> obm = ObservationModule(obs, scene_general=scene_general)
>>> obm.nextObservation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local/tmp/anaconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/observation_module/observation_module.py", line 175, in nextObservation
    self.instrument.reset(ra, dec, pa, filter, self.obs_count)
  File "/local/tmp/anaconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/instruments/instrument.py", line 128, in reset
    self.background = self.pixel_background/(self.oversample*self.oversample)
  File "/local/tmp/anaconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/instruments/instrument.py", line 893, in pixel_background
    obs = ps.Observation(sp, self.bandpass)
  File "/local/tmp/anaconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/instruments/instrument.py", line 796, in bandpass
    i = self.pandeia_instrument
  File "/local/tmp/anaconda3/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/instruments/instrument.py", line 838, in pandeia_instrument
    self._instrument = InstrumentFactory(config=conf)
  File "/local/tmp/anaconda3/envs/forSTIPS/lib/python2.7/site-packages/pandeia/engine/instrument_factory.py", line 51, in InstrumentFactory
    cls = inst_map[instrument](mode=mode, config=config, webapp=webapp, **kwargs)
  File "/local/tmp/anaconda3/envs/forSTIPS/lib/python2.7/site-packages/pandeia/engine/wfirst.py", line 33, in __init__
    Instrument.__init__(self, telescope=telescope, mode=mode, config=config, **kwargs)
  File "/local/tmp/anaconda3/envs/forSTIPS/lib/python2.7/site-packages/pandeia/engine/instrument.py", line 111, in __init__
    self.exposure_spec = self.get_exposure_pars()
  File "/local/tmp/anaconda3/envs/forSTIPS/lib/python2.7/site-packages/pandeia/engine/instrument.py", line 628, in get_exposure_pars
    det_type = self.get_detector_pars()['det_type']
KeyError: 'det_type'
```

**Comment by york-stsci** [comment]
Based on the above, I can see two issues with your installation.

First, the particular error you're encountering is a result of Pandeia 1.1.1 breaking WFIRST functionality (i.e. the wfirst-specific parts of pandeia_refdata were *not* updated when the JWST parts were, and as such you can't use them together. I think that, for public use, I still suggest using Pandeia 1.0. I don't know whether the upcoming Pandeia 1.2 will fix this or not.

Second, you didn't set the environment variable WEBBPSF_PATH to point to your webbpsf data directory. STIPS won't fail to run without it, but it *will* crash when it tries (and fails) to create a PSF.

**Comment by rubab1** [comment]
After switching to Pandeia 1.0, continuing from previous post otherwise:
```
>>> obm.nextObservation()

(bp__H158) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.

(bp__H158) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.

(bp__H158) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.

/local/tmp/anaconda3/envs/forSTIPS/lib/python2.7/site-packages/pysynphot/units.py:851: RuntimeWarning: divide by zero encountered in log

  return -1.085736 * N.log(arg) + STZERO

0

>>> source_count_catalogues = obm.addCatalogue('Mixed_h15_shell_5Mpc_H.tbl')

>>> psf_file = obm.addError()

(bp__H158) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.

(bp__H158) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.

```

Since the job did not crash up to this point and assuming that these screen outputs are info/warnings and not errors, we manually killed the job at this point and are going to repeat the same on a machine with adequate memory (and make sure that RA/DEC centers etc. agree with the input file). In the meantime, @york-stsci please let me know in case the 'defined binset ...' messages might be critical errors.

Other notes:
- Please update the README to specify Pandeia 1.1.1 limitations
- The astroconda distribution of webbpsf 0.6.0 includes data files needed and does not require manually setting the path to associated data
```
$ source activate forSTIPS
$ echo $WEBBPSF_PATH
/local/tmp/anaconda3/envs/forSTIPS/share/webbpsf-data
$ ls /local/tmp/anaconda3/envs/forSTIPS/share/webbpsf-data
AFTA_CGI_C5_Pupil_onax_256px_flip.fits	JWpupil_segments.fits  NIRSpec	       jwst_pupil_RevW_npix1024.fits.gz   tricontagon_oversized_4pct.fits.gz  wfc_pupil_rev_mcr.fits
CGI					MIRI		       README.md       jwst_pupil_RevW_npix16384.fits.gz  upscaled_HST_OPD.fits
FGS					NIRCam		       WFI	       jwst_pupil_RevW_npix2048.fits.gz   version.txt
IFC					NIRISS		       conda_build.sh  tricontagon.fits.gz		  wfc_pupil_masked_rev_mcr.fits
$ ls /local/tmp/anaconda3/envs/forSTIPS/share/webbpsf-data/WFI
filters  filters.tsv  wim_zernikes_cycle6.csv
```
- The 'obm.nextObservation()' step created large *.tmp files. Will post updates here regarding whether they persist after a completed run and/or might be related to issue #5 
```
$ ls -lh
total 1.8G
-rw-r--r-- 1 rubab rubab 9.6M Dec 20 19:46 Mixed_h15_shell_5Mpc_H.tbl
-rw-rw-r-- 1 rubab rubab 4.5M Dec 21 11:04 _c609defdf52449c494a0631035c174a3_WFI H158 PSF.tmp
-rw-rw-r-- 1 rubab rubab 1.8G Dec 21 11:04 sim_d7029b1e0abd4b4d9063e042ac3269f0_WFIRST-WFI.tmp
```

**Comment by rubab1** [comment]
We confirm that the following steps sufficed in our case to install STIPS from the bugfix branch to run a test simulation locally, having downloaded the pysynphot and pandeia data files first.
```
conda create -n forSTIPS python=2.7.12 astropy=1.3.2 numpy=1.12.1 scipy=0.18.1 photutils=0.3.2 pysynphot=0.9.8.5 webbpsf=0.6
source activate forSTIPS
echo $WEBBPSF_PATH
export PYSYN_CDBS="/local/tmp/Work/bin/grp/hst/cdbs"
pip install "esutil==0.6.0"
pip install "montage-wrapper==0.9.9"
pip install "jwst_backgrounds==1.1.1"
pip install "pandeia.engine==1.0"
export pandeia_refdata="/local/tmp/Work/bin/pandeia_data-1.0"
cd /local/tmp/Work
git clone https://github.com/spacetelescope/STScI-STIPS-UI.git
export stips_data="/local/tmp/Work/STScI-STIPS-UI/sim_input/stips_data"
git clone https://github.com/spacetelescope/STScI-STIPS.git
cd STScI-STIPS
git checkout bugfix
python setup.py install
mkdir ~/test_STIPS
cd ~/test_STIPS
./test1.py
```
Contents of various files:
```
$ cat test1.py
#! /usr/bin/env python
from stips.observation_module import ObservationModule
obs = {'instrument': 'WFI', 'filters': ['H158'], 'detectors': 1, 'distortion': False, 'oversample': 10, 'pupil_mask': '', 'background': 'avg', 'observations_id': 1, 'exptime': 10000, 'offsets': [{'offset_id': 1, 'offset_centre': False, 'offset_ra': 0.5, 'offset_dec': 0.0, 'offset_pa': 27.0}]}
scene_general = {'ra': 254.56583104, 'dec': 24.10779887, 'pa': 0.0, 'seed': 1234}
obm = ObservationModule(obs, scene_general=scene_general)
obm.nextObservation()
source_count_catalogues = obm.addCatalogue('Mixed_h15_shell_5Mpc_H.tbl')
psf_file = obm.addError()
fits_file, mosaic_file, params = obm.finalize(mosaic=False)
$ head -n 10 Mixed_h15_shell_5Mpc_H.tbl 
\type = internal
\filter = H158
\center = (254.56583104  24.10779887)
|        id|             ra|            dec|           flux|    type|         n|             re|            phi|          ratio|   notes|
|    double|         double|         double|         double|    char|    double|         double|         double|         double|    char|
|          |               |               |               |        |          |               |               |               |        |
|      null|           null|           null|           null|    null|      null|           null|           null|           null|    null|
          1     254.5828521      24.0578450       0.8198854    point      1.000       1.0000000       1.0000000       1.0000000  comment 
          2     254.5795835      24.1068677       0.1669516    point      1.000       1.0000000       1.0000000       1.0000000  comment 
          3     254.6017628      24.0870851       2.2881686    point      1.000       1.0000000       1.0000000       1.0000000  comment 
$ tail -n 5 Mixed_h15_shell_5Mpc_H.tbl 
      72695     254.5070958      24.1499511       0.0631276   sersic      0.905       1.6620000      -2.5870000       0.8564000  comment 
      72696     254.5240014      24.1182974      10.1090888   sersic      1.169       0.2230000      13.0960000       0.0962000  comment 
      72697     254.5851262      24.1062584       0.3476480   sersic      3.417       0.5530000      16.8260000       0.9925000  comment 
      72698     254.5156673      24.1407745       0.0825936   sersic      1.893       1.5290000      84.8090000       0.6852000  comment 
      72699     254.5207282      24.0820472       3.0574265   sersic      2.945       0.8680000     -43.5690000       0.0304000  comment 
$ ls  *.fits
sim_1_0.fits  sim_1_0_psf.fits
$ fitsheader sim_1_0.fits  -e 0
# HDU 0 in sim_1_0.fits:
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                    8 / array data type                                
NAXIS   =                    0 / number of array dimensions                     
EXTEND  =                    T                                                  
$ fitsheader sim_1_0.fits  -e 1 | head -n 15
# HDU 1 in sim_1_0.fits:
XTENSION= 'IMAGE   '           / Image extension                                
BITPIX  =                  -32 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                 4096                                                  
NAXIS2  =                 4096                                                  
PCOUNT  =                    0 / number of parameters                           
GCOUNT  =                    1 / number of groups                               
WCSAXES =                    2 / Number of coordinate axes                      
CRPIX1  =               2048.0 / Pixel coordinate of reference point            
CRPIX2  =               2048.0 / Pixel coordinate of reference point            
PC1_1   =     0.89100652418836 / Coordinate transformation matrix element       
PC1_2   =    -0.45399049973956 / Coordinate transformation matrix element       
PC2_1   =    -0.45399049973956 / Coordinate transformation matrix element       
PC2_2   =     0.89100652418836 / Coordinate transformation matrix element 
``` 
Warnings produced during the run included:
```
(bp__H158) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.

/local/tmp/anaconda/envs/forSTIPS/lib/python2.7/site-packages/pysynphot/units.py:851: RuntimeWarning: divide by zero encountered in log

  return -1.085736 * N.log(arg) + STZERO
```
We request confirmation that the missing "defined binset in the wavecat table" and "divide by zero" issues are understood and/or inconsequential.

Closing issue.
