### ISSUE TITLE
import error for GriddedPSFModel

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#85]
I can't seem to import the GriddedPSFModel in my NASA Pleiades installation:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nobackupp11/bwilli24/STScI-STIPS/stips/__init__.py", line 22, in <module>
    from .astro_image import AstroImage
  File "/nobackupp11/bwilli24/STScI-STIPS/stips/astro_image/__init__.py", line 4, in <module>
    from .astro_image import AstroImage
  File "/nobackupp11/bwilli24/STScI-STIPS/stips/astro_image/astro_image.py", line 14, in <module>
    from photutils.psf.models import GriddedPSFModel
ImportError: cannot import name 'GriddedPSFModel'
>>> 

Installation goes fine:
Using /nobackupp11/bwilli24/miniconda3/envs/STIPS/lib/python3.6/site-packages
Finished processing dependencies for stips==1.0.8

(STIPS) bash-4.3$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
(STIPS) bash-4.3$ 

I'll dig for a solution, but thought I'd post it here in case it comes up again.

**Comment by benw1** [comment]
Turns out this is due to my photutils version being too old.  Updating it fixed the problem.  Perhaps that dependency should be added to setup.py.
